// Content for the Compassus vendor demo question guide.
module.exports = {
  common: [
    { t: "The referral decision",
      q: "It's 10am and a referral lands. Show us what your product tells the person deciding whether to accept it — and what happens next if we say yes.",
      r: "Only Axle Health and Arya gave a real referral-against-capacity mechanism in their returns. HCHB does not forecast referrals or discharges; CareStitch never addresses inflow against the envelope; VitalisCare's branch rollup is planned; MedArrive's referral check is Q4 roadmap. This is the front door of the operating model and most of the market has not built it. It is also the natural opening of the walkthrough we have asked for." },
    { t: "The episode, not the visit",
      q: "Show us how ordered frequency, the recert window and the LUPA threshold shape the week your product builds — and what it does when an episode starts falling behind.",
      r: "The fluency test with teeth. PDGM, LUPA, OASIS and recert are absent from almost every return in the field. Axle used the vocabulary unprompted, MedArrive earned it in a different business, and the rest are silent. Asked of all six, this separates home health from home care within a minute, and it cannot be answered from a slide deck." },
    { t: "HCHB freshness, with a number",
      q: "HCHB is our system of record and stays that way. What do you read, what do you write, by what mechanism, and how stale can the data be at worst? We have been given three different answers on HCHB's own refresh lag — give us yours, with a number.",
      r: "There is a live factual conflict across the returns. Arya claims sub-five-minute latency via screen automation; Axle Health turned their integration off over a lag of up to thirty minutes; HCHB says there is no latency because it is native; CareConnect's plan assumes roughly twenty minutes on a read replica. Someone is wrong. Asking all six triangulates it, and the answer matters well beyond vendor selection." },
    { t: "The line between advise and decide",
      q: "Where does your product decide on its own today, and where does a person confirm? Name a customer who moved that line — which direction, and what happened.",
      r: "Sophistication marks across the field span 2 to 4. Arya writes back to HCHB with no approval step; Axle can run autonomously but every real customer kept a human in the loop; HCHB stops short deliberately. The same question to six vendors is the fastest way to find where our own Assist boundary should actually sit." },
    { t: "The clinician says no",
      q: "A clinician rejects an assignment. Walk us through the next sixty seconds, and the next sixty days — what happens on the schedule, and what changes in the model.",
      r: "Clinician fit is the weakest scored section in the entire field: 0.25 to 0.75, nobody higher. Several returns describe a feedback loop and never describe the moment. Our own discovery work is unambiguous that change management, not algorithm quality, decides whether a tool like this survives contact with tenured clinicians." },
    { t: "A Tuesday that goes wrong",
      q: "Two call-outs at 7am, a patient reschedules, and one visit is at the edge of its compliance window. Show the day re-form: how fast, who gets contacted, and what happens when nobody takes the visit.",
      r: "Exception handling is where these products genuinely differ, and 'what happens when nobody takes it' went unanswered by several vendors. Make them do this live rather than describe it — the difference between a real recovery loop and a dashboard becomes obvious in about ninety seconds." },
    { t: "What you don't do",
      q: "Name the three things in our scope your product does not do today. For each: a date, a workaround, or never. We will hold this against your Section B answers.",
      r: "Multiple returns claim coverage in the self-assessment that the mechanism answers do not support — our rubric already says believe Section C over Section B. This question rewards the candor we score and resolves the contradictions cheaply. A vendor who claims everything has told us something." },
    { t: "What breaks at our size",
      q: "Here is our scale. What is your largest deployment, what broke when you got there, and what would you do differently starting with us?",
      r: "Durability came back Neutral or unaddressed for five of the six advancing vendors — no company size, no funding stage, no statement of how central home health is to the business. This gets at the same ground without asking a question they are practised at deflecting." },
    { t: "The one number you'd stake it on",
      q: "One measured result, one named customer: what it was before, what it is now, over what period, and how the baseline was set. One is enough if it is real.",
      r: "Measured impact was flagged Watch for nearly the whole field — results claimed with no baseline and no period. Only Arya and HCHB cleared the bar. Asking for a single verifiable number is more informative than asking for more claims." },
    { t: "Where you'll look worse",
      q: "We are running six of these conversations. Where do you expect to compare unfavourably, and what context would we be missing if we scored you on that alone?",
      r: "This is the spectrum-of-context mechanism made explicit: every vendor gets the floor to explain a weak spot rather than being scored on a single return read in isolation. The answer is also a candor read in its own right — vendors who name their real gap tend to be the ones telling the truth everywhere else." } ],

  vendors: [
    { name: "Arya", score: "84 · Advance · no open stop-checks",
      posture: "The strongest return in the field. These questions ask whether the strength is where we need it.",
      qs: [
        { q: "How many of your roughly sixty production organizations are on HCHB, how many bi-directionally in production, and since when?",
          r: "The return describes a live, bi-directional HCHB integration since mid-2025 but never gives an HCHB-specific customer count. Sixty orgs across all EHRs is a different claim from a proven HCHB footprint, and our scorecard's own closing note flags this as the first thing to ask." },
        { q: "Your integration is Citrix screen automation. What happens when HCHB changes a screen — who notices, who fixes it, how fast, and has it broken in production yet?",
          r: "Screen automation is the most fragile integration pattern in the field. It works until the vendor changes a layout. We need to know whether they have a detection mechanism and a repair SLA, or whether our schedule silently stops updating one Tuesday morning." },
        { q: "You are the only vendor scored at 'Runs it' — writing back to HCHB with no approval step. Which actions, at which customer? And can every one of them be configured to require approval permanently, not as a phase-one setting we are expected to graduate out of?",
          r: "This is the one place where a top mark signals risk rather than strength. Full autonomous execution on assignment and coverage sits beyond the Assist boundary we have set for ourselves. We need to know the boundary is a permanent configuration, not a training-wheels phase." },
        { q: "'No more apps for clinicians, ever.' Walk us through a clinician's actual week under that model. What happens to the clinician who will not engage with an agent by voice or text?",
          r: "It is their strongest philosophical position and their largest adoption risk. If the only channel to the clinician is an agent conversation, the clinician who ignores it becomes invisible to the system. Our clinicians are professionally independent and vocal about their own week." },
        { q: "Before-the-visit automation is live at one customer and you recommend staging it late. What is the realistic sequence and date for us?",
          r: "Engagement scored 0.83 largely on mechanism rather than proof — the pre-visit layer is self-disclosed as live with a single customer. Honest, and it means the patient-facing arena is further out than the score suggests." },
        { q: "Aveanna — eleven percent more authorized hours delivered. Was that private duty or home health?",
          r: "It is the headline number in the return and the only named reference. Aveanna's business spans private duty nursing and personal care as well as home health, and those are different scheduling problems. We need to know which one produced the result before we let it carry weight." },
        { q: "Your customer mix is described as 'an even split.' Give us the actual percentages. And tell us company size, funding stage, and how central home health is versus your other post-acute settings.",
          r: "Durability is not addressed anywhere in the return — no size, no funding, no market focus. 'Even split' is the only description of the customer base and it is not a number." } ] },

    { name: "HCHB", score: "75 · Consider · one open stop-check",
      posture: "The incumbent, and native rather than integrated. Two of these are uncomfortable and both need asking.",
      qs: [
        { q: "Your twelve-month uptime figure, and the contractual commitment with remedies.",
          r: "OPEN STOP-CHECK. The return contains neither. Under our own rules this was to be resolved before advancing, not traded against points — a product carrying the work of hundreds of schedulers cannot have an undefined continuity posture. This is the first question of the call." },
        { q: "Partnership scored 1 of 4, the lowest in the field. Co-marketing is not a partnership. Is there any structure available — design partner terms, a roadmap seat, shared economics, ownership — or is this a standard license?",
          r: "Every other vendor in the round offered at least design-partner terms, and one offered equity unprompted. Given the investment we are making, a standard license is a materially different proposition and we should establish that in the room rather than in a contract redline." },
        { q: "Your automations depend on accurate and timely documentation in HCHB. Late and incomplete documentation is our daily reality. What does the product do with bad data, rather than assume good data?",
          r: "Their scheduling answer is explicit that everything 'has to be in HCHB.' Our discovery work identified clinical documentation lag as one of the primary upstream causes of scheduling failure. A product that assumes clean inputs is solving a problem we do not have." },
        { q: "'Agency configuration' carries a lot of weight in your answers. Who configures it, how long does it take, what does it cost, and what does a misconfiguration look like in production?",
          r: "Several capacity capabilities are described as working 'when configured by branch.' Across eighty-plus branches, configuration burden is the difference between a capability and a capability we will never actually have." },
        { q: "You do not forecast future referrals or discharges. We are being asked to run capacity against future demand — what fills that gap, and is it on the roadmap with a date?",
          r: "Stated plainly in their own capacity answer. Forward demand is the half of capacity management that lets a branch leader say yes or no to a referral with confidence, and it is the half they do not cover." },
        { q: "Visit Finder is new and you were not sure who is using it. Name a live customer, or tell us it is pre-release.",
          r: "Half of the 'when plans change' capability rests on it. Find Shifts is real and detailed; Visit Finder was described without a user. We should know which we are buying." },
        { q: "Show us the clinician's actual interface — what they can see, change and request about their own week.",
          r: "Clinician fit scored 2 of 4 mainly because the return never describes the clinician's controls. This is the single largest determinant of adoption and we are currently guessing." },
        { q: "You are our EHR. If we invest a dedicated team in building this with you, what stops it shipping to every competitor next quarter? Is there any lead time or exclusivity on the table?",
          r: "Unique to this vendor. Everything co-developed with the system of record is, by default, a product enhancement available to the whole customer base. That may be acceptable — but it should be a decision we make knowingly, with a lead-time question asked out loud." } ] },

    { name: "VitalisCare", score: "67 · Consider · no open stop-checks",
      posture: "A live HCHB integration and rigorous impact numbers. The question is whether any of it is home health.",
      qs: [
        { q: "Six production customers since 2023 — how many are home health versus hospice, and what is the largest home health census? Demo a home health branch, not a hospice one.",
          r: "The integration is genuinely live and has been for three years, but the live history is hospice with limited home health. Hospice scheduling carries neither PDGM economics nor therapy disciplines, so the proven ground may not overlap our problem at all." },
        { q: "Your return mentions RN and HHA, never PT, OT or SLP. Does the product schedule therapy disciplines at all — eval-driven frequency, therapy sequencing, discipline-specific productivity?",
          r: "Therapy is a large share of our visit volume and behaves differently from nursing: evaluation-driven frequency, different productivity math, different sequencing within the episode. Its complete absence from the return is either an oversight or a gap in the product." },
        { q: "Walk us through a sixty-day Medicare episode: the SOC window, the recert window, LUPA risk.",
          r: "PDGM, LUPA, OASIS, SOC/ROC and recert appear nowhere in this return — the vocabulary is hospice and home care throughout. Either the fluency exists and did not make it onto the page, or it does not exist. The demo settles it." },
        { q: "No patient-facing communication of any kind exists today and no date was given. What is the plan, what does it cost, and when — or do we keep doing that work manually?",
          r: "This scored a zero, the only one in the arena among the advancing vendors. Engagement is a third of our stated scope; a permanent gap here changes the shape of the deal." },
        { q: "You admitted authorization and readiness are not tracked states. How do not-ready visits stay off the schedule today?",
          r: "A creditable admission, and a structural one. The distinction between a visit that is unready — a paperwork problem — and one that is unassigned — a staffing problem — is the backbone of scheduling triage." },
        { q: "Point-weighting and the branch rollup are both 'planned.' Dates, and who funds that build.",
          r: "The point system is the shared currency of capacity and scheduling in our own model, and a branch-level rollup is how a leader sees the envelope. Both being planned means the capacity half is not yet real for us." },
        { q: "Company size, funding, headcount. Would we be your largest customer by a multiple?",
          r: "Durability is unaddressed. Six customers since 2023 is a small base, and being a vendor's outsized flagship account carries its own risk regardless of product quality." },
        { q: "Name the actual product set — Sync, Sync360, the mobile app. What requires which, and what does a clinician have to install?",
          r: "The return refers to the product inconsistently and leans on a mobile app whose role is unclear. Another required app for clinicians is a material adoption cost and we should price it before, not after." } ] },

    { name: "Axle Health", score: "63 · Conditional — Hold · no open stop-checks",
      posture: "The best product answers in the field attached to a zero on integration. This call is mostly one question.",
      qs: [
        { q: "You built the HCHB write-back and turned it off over a thirty-minute refresh lag. What specifically lags, what is your threshold, and what has to change for it to be viable? Is the Databricks/Snowflake migration a commitment HCHB has made to you with a date, or your read of where they are going?",
          r: "This is the whole decision. Everything else in their return scores at or near the top of the field, and the integration scores zero — the only zero any advancing vendor received. Turning off a working integration on quality grounds is also the single most creditable act of candor in the process, which makes the answer worth hearing carefully." },
        { q: "Would you turn it back on for Compassus — read-only first, full write-back later, or not at all? Give us a date and what you need from us.",
          r: "A conditional band lifts only on a date. Without one, the product conversation is hypothetical no matter how strong the product is." },
        { q: "Your continuity answer says the integration is 'always bi-directional.' It is off. Reconcile those two statements.",
          r: "A direct internal contradiction in the return, flagged at scoring. It is probably careless drafting rather than misdirection — but we should hear which, because the same language would be in a contract." },
        { q: "Which EHRs do your twenty-five customers actually run, including the eleven-thousand-ADC deployment? What would be different about integrating us?",
          r: "Their scale is real and their home health concentration is the second-highest in the field at eighty percent. Knowing which records they integrate with today tells us whether HCHB is an anomaly for them or simply the next one." },
        { q: "Your partnership answer reads rushed — referral credits and general openness, no structure. Given what we are putting in, what is the real proposal?",
          r: "Partnership scored 2 of 4, second lowest in the field, and the section reads as though it was written last. Given a design partnership, a dedicated team and co-marketing on our side, the asymmetry is worth naming." },
        { q: "Incentives are a manual waitlist and dynamic pricing is in development. Date, and what do we do in the interim?",
          r: "An admitted gap, and a field-wide one — nobody has built this properly. Hard-to-fill visits are where incentive mechanics earn their keep, so the interim answer matters as much as the roadmap." },
        { q: "There is no name on your return. Who is on this call, and who would actually run our deployment?",
          r: "The return reads like someone close to the product, except in the partnership section. Knowing who wrote it, and whether that person stays with the account, is part of what we are buying." },
        { q: "Company size, funding, how central home health is to the business.",
          r: "Unaddressed anywhere in the return, as with most of the field." } ] },

    { name: "CareStitch", score: "56 · Conditional — Hold · no open stop-checks",
      posture: "The highest home health concentration in the field at sixty-nine percent, and the thinnest integration story.",
      qs: [
        { q: "Your HCHB beta is read-only screen automation that has never run in production, with no go-live date. Give us a date for read, a date for write-back, and the engineering plan behind both.",
          r: "This is the entire reason they sit Conditional. A beta that has never carried production traffic is a prototype, and the separate manual-upload path — where the agency uploads HCHB reports — is a workaround rather than an integration." },
        { q: "The manual-upload path: is that what your HCHB customers actually do today? How many HCHB customers do you have?",
          r: "With seventy-nine organizations and sixty-nine percent home health, some are certainly on HCHB. How those customers operate today tells us what our first year would really look like." },
        { q: "You ingest no orders and no authorization from HCHB, and do not enforce compliance windows. That is the spine of home health scheduling. Plan and date.",
          r: "Three admissions, all unprompted and all structural. Ordered visits, authorization status and compliance windows are the inputs that make a home health schedule legal as well as efficient." },
        { q: "You scored lowest of the six on sophistication — you filter and display, and the scheduler makes every call. Is 'advise and orchestrate' a principle you will hold, or a stage you will move past? What would it take to reach recommend?",
          r: "Their framing is coherent and may even suit our clinician culture. But at 'Checks it' the product leaves the scheduler doing the work, which is the cost line the initiative exists to move." },
        { q: "References were 'expected,' not committed. We need three named home health references in writing before the next round.",
          r: "Our rubric treats references as a significant part of the process. An expectation is not a commitment, and this is the cheapest of all the open items to close." },
        { q: "Front-loading is scheduler-driven rather than paced by the product. Under PDGM, pacing is where the money is. Will the product ever pace the episode itself?",
          r: "Front-loading and visit pacing against the plan of care are where episode economics are won or lost. Leaving it to the scheduler preserves exactly the manual burden we are trying to remove." },
        { q: "Sixty-nine percent home health across seventy-nine organizations and one hundred forty-four branches is the strongest concentration here — show us that. Which organizations, which EHRs, what size?",
          r: "It is their real advantage and the return asserts rather than demonstrates it. If the concentration is genuine it partly offsets the integration gap; this question gives them the chance to prove it." },
        { q: "How central is home health to CareStitch's business as a whole? Company size and funding.",
          r: "Not addressed. The concentration figure describes the customer mix, not the company's commitment or its runway." } ] },

    { name: "MedArrive", score: "48 · Conditional — Decline · two open stop-checks",
      posture: "Advanced from below the decline line. This call is about whether they belong in the round — be straight with them, and with ourselves.",
      qs: [
        { q: "Zero home health, hospice or private duty customers. Is there a signed or in-flight home health customer? Would we be the first?",
          r: "OPEN STOP-CHECK. Every reference and every adoption number in the return comes from hospital-at-home and primary care in the home. Being a vendor's first customer in a market is a decision we can make deliberately — but only with the fact on the table." },
        { q: "Your ROI study is hospital-at-home. Which of those results should transfer to a home health branch, and which should not?",
          r: "OPEN STOP-CHECK, and an opportunity as much as a challenge. They declined to use their old field-services numbers as evidence because that business no longer exists, which is creditable and leaves them with nothing from our market. Let them make the transfer argument themselves." },
        { q: "LUPA pacing, the recert window, the readiness check and the referral-capacity check — you describe all four in real detail and all four are roadmap. Which exist in code today? Show them running. What is the build plan, and who pays for it?",
          r: "This is the defining pattern of their return: everything home-health-specific is described with genuine fluency and marked as not built. The fluency is real, earned running their own field operation. The code is the open question." },
        { q: "Your narrative describes a working ranked coverage-suggestion feature; your status line calls it roadmap. Which is true?",
          r: "A direct internal contradiction flagged at scoring. Coverage recovery is a core capability and we need to know which of the two statements to believe." },
        { q: "Clinician fit scored lowest in the field. Your six-month adoption numbers are real but come from gig field clinicians. Salaried home health clinicians with established caseloads and strong feelings about their own week behave nothing like that. What transfers?",
          r: "They scored 1 of 4, the only score that low anywhere in the process, and the adoption evidence is strong but drawn from a different workforce model. Our own discovery is emphatic that clinician behaviour, not product capability, decides these rollouts." },
        { q: "You have pivoted once already — from running a seven-hundred-clinician field operation to selling software — and are now aimed at a market you have never served. Funding, runway, headcount, and what happens if home health does not land.",
          r: "Durability was marked Concern, the only one among the advancing vendors. This is a fair question to ask plainly rather than infer." },
        { q: "You have chosen not to build agentic voice. Most of the coverage problem is outreach. What fills that?",
          r: "A deliberate and clearly stated boundary, which we respect — but outreach to clinicians and patients is where a large share of the manual effort sits. We should understand the alternative before assuming there is one." },
        { q: "What would make us wrong to rule you out?",
          r: "The fairest question we can ask a vendor in this position, and the most informative. How they answer it tells us as much as anything else in the two hours." } ] } ]
};
